name: 提交简化记录（仅层数）
description: 提交成功单通层数记录，不包含通关时间
title: "[层数记录] "
labels: ["层数记录"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📊 简化记录提交表单
        
        此表单用于仅提交单通层数记录，不包含通关时间信息。
        
        **注意事项：**
        - 请确保选择正确的罪人和人格
        - 该记录仅显示在"单通层数（联网）"排行榜中
        - 提交后需等待管理员审核（添加"已审核"标签后自动更新排行榜）
        - 更新通常在审核后几分钟内完成

  - type: dropdown
    id: sinner-name
    attributes:
      label: 罪人名称
      description: 选择您使用的罪人
      options:
        - 李箱 (Yi Sang)
        - 浮士德 (Faust)
        - 堂吉诃德 (Don Quixote)
        - 良秀 (Ryoshu)
        - 默尔索 (Meursault)
        - 鸿璐 (Hong Lu)
        - 希斯克利夫 (Heathcliff)
        - 以实玛利 (Ishmael)
        - 罗佳 (Rodion)
        - 辛克莱 (Sinclair)
        - 格里高尔 (Gregor)
        - 奥提斯 (Outis)
    validations:
      required: true

  - type: dropdown
    id: persona-name
    attributes:
      label: 人格名称
      description: 选择您使用的人格（请根据您选择的罪人选择对应人格）
      options:
        - "--- 李箱 (Yi Sang) 的人格 ---"
        - W公司3级清扫人员
        - Seven协会南部6科
        - N公司E.G.O:凶弹
        - LCE E.G.O:提灯
        - LCB罪人
        - Dieci协会南部4科
        - 绽放E.G.O:山茶花
        - 裴廓德号大副
        - 脑叶公司E.G.O:庄严哀悼
        - 六协会南部3科
        - 臼齿事务所收尾人
        - 剑契组杀手
        - 环指点彩派学徒
        - 黑兽-午魁首
        - "--- 浮士德 (Faust) 的人格 ---"
        - し协会东部3科
        - Zwei协会南部4科
        - W公司2级清扫人员
        - Seven协会南部4科
        - LCE_E.G.O:红艳煞
        - LCB罪人(浮士德)
        - 执柄者
        - 脑叶公司E.G.O:悔恨
        - 脑叶公司幸存者
        - 剑契组杀手(浮士德)
        - 呼啸山庄管家
        - 黑兽-卯魁首
        - 多裂纹事务所代表
        - "--- 堂吉诃德 (Don Quixote) 的人格 ---"
        - し协会南部5科科长
        - W公司3级清扫人员(堂吉诃德)
        - T公司3级征收人员
        - N公司中锤
        - LCB罪人(堂吉诃德)
        - Cinq协会南部5科科长
        - Cinq协会东部3科
        - 中指幼妹
        - 脑叶公司E.G.O:以爱与憎之名
        - 脑叶公司E.G.O:提灯(堂吉诃德)
        - 拉·曼却领总督
        - 剑契组杀手(堂吉诃德)
        - 黑兽-未
        - "--- 良秀 (Ryoshu) 的人格 ---"
        - W公司3级清扫人员(良秀)
        - Seven协会南部6科(良秀)
        - N公司E.G.O:轻蔑，敬畏
        - LCCB系长
        - LCB罪人(良秀)
        - 脑叶公司E.G.O:赤瞳·忏悔
        - 六协会南部4科
        - 良·派厨师长
        - 鸿园的流浪武者
        - 黑云会若众
        - 黑兽-卯
        - 埃德加家族首席管家
        - 20区圣愚
        - "--- 默尔索 (Meursault) 的人格 ---"
        - W公司2级清扫人员(默尔索)
        - R公司第四集团军犀牛队
        - N公司大锤
        - LCB罪人(默尔索)
        - Dieci协会南部4科科长
        - Cinq协会西部3科
        - 中指幼弟
        - 死兔帮老大
        - 拇指东部指挥官IIII
        - 玫瑰扳手工坊收尾人
        - 六协会南部6科
        - 拉·曼却领王子
        - 剑契组头领
        - "--- 鸿璐 (Hong Lu) 的人格 ---"
        - W公司2级清扫人员(鸿璐)
        - R公司第四集团军驯鹿队
        - LCB罪人(鸿璐)
        - K公司3级摘除人员
        - Dieci协会南部4科(鸿璐)
        - 六协会南部5科
        - 猎牙事务所收尾人
        - 句点事务所代表
        - 鸿园的君主
        - 黑云会若众(鸿璐)
        - 豆豆帮帮主
        - 吊钩事务所收尾人
        - 20区圣愚(鸿璐)
        - "--- 希斯克利夫 (Heathcliff) 的人格 ---"
        - し协会南部5科
        - W公司4级清扫人员-CCA
        - Seven协会南部4科(希斯克利夫)
        - R公司第四集团军兔子队
        - Öufi协会南部3科
        - N公司小锤
        - LCB罪人(希斯克利夫)
        - 裴廓德号鱼叉手
        - 脑叶公司E.G.O:狐雨
        - 狂猎
        - 句点事务所收尾人(希斯克利夫)
        - 黑云会若众(希斯克利夫)
        - 黑兽-酉魁首
        - 多裂纹事务所收尾人
        - "--- 以实玛利 (Ishmael) 的人格 ---"
        - し协会南部5科(以实玛利)
        - Zwei协会西部3科
        - R公司第四集团军驯鹿队(以实玛利)
        - LCCB系长(以实玛利)
        - LCB罪人(以实玛利)
        - 裴廓德号船长
        - 脑叶公司E.G.O:荡漾
        - 六协会南部4科(以实玛利)
        - 臼齿修船厂收尾人
        - 家主候选人
        - 黑云会副会长
        - 定事务所代表
        - 埃德加家族管家
        - "--- 罗佳 (Rodion) 的人格 ---"
        - Девять协会北部3科
        - Zwei协会南部5科
        - T公司2级征收人员
        - N公司中锤(罗佳)
        - LCCB系长(罗佳)
        - LCB罪人(罗佳)
        - Dieci协会南部4科(罗佳)
        - 脑叶公司E.G.O:泪锋之剑
        - 玫瑰扳手工坊代表
        - 六协会南部4科科长
        - 拉·曼却领公主
        - 黑云会若众(罗佳)
        - 黑兽-巳
        - "--- 辛克莱 (Sinclair) 的人格 ---"
        - Девять协会北部3科(辛克莱)
        - Zwei协会西部3科(辛克莱)
        - Zwei协会南部6科
        - LCB罪人(辛克莱)
        - Cinq协会南部4科科长
        - 准执柄者
        - 中指幼弟(辛克莱)
        - 脑叶公司E.G.O:朱符
        - 拇指东部士兵II
        - 流浪乐队头目
        - 黎明事务所收尾人
        - 臼齿修船厂收尾人(辛克莱)
        - 剑契组杀手(辛克莱)
        - 黑兽-酉
        - "--- 格里高尔 (Gregor) 的人格 ---"
        - Zwei协会南部4科(格里高尔)
        - LCB罪人(格里高尔)
        - G公司科长代理
        - 夜锥组队长
        - 炎拳事务所幸存者
        - 双钩海盗团大副
        - 玫瑰扳手工坊收尾人(格里高尔)
        - 六协会南部6科(格里高尔)
        - 良·派帮厨
        - 拉·曼却领神父
        - 黑云会副会长(格里高尔)
        - 黑兽-巳(格里高尔)
        - 埃德加家族继承人
        - "--- 奥提斯 (Outis) 的人格 ---"
        - W公司3级清扫组长
        - T公司3级强制征收人员
        - Seven协会南部6科科长
        - LCB罪人(奥提斯)
        - G公司部长
        - Cinq协会南部4科(奥提斯)
        - 脑叶公司E.G.O:魔弹
        - 拉·曼却领理发师
        - 臼齿事务所收尾人(奥提斯)
        - 剑契组杀手(奥提斯)
        - 环指点彩派学徒(奥提斯)
        - 呼啸山庄首席管家
        - 黑兽-卯(奥提斯)
    validations:
      required: true

  - type: dropdown
    id: floor-level
    attributes:
      label: 单通层数
      description: 您成功单通的最高层数
      options:
        - 第5层
        - 第10层
        - 第15层
    validations:
      required: true

  - type: input
    id: run-date
    attributes:
      label: 通关日期
      description: 完成通关的日期（YYYY-MM-DD格式）
      placeholder: "例如：2025-12-12"
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: 备注（可选）
      description: 任何额外的说明或备注
      placeholder: "例如：策略说明、难度等"
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: 提交确认
      description: 请确认以下内容
      options:
        - label: 我确认以上信息准确无误
          required: true
